version: "3.7"

services:

  api:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - 9000:9000
    networks:
      - server
 
  mongodb:
    image: mongo:3.6.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      # default db
      MONGO_INITDB_DATABASE: DB
      # authenticationDatabase
      MONGO_INITDB_AUTH: "true"
      MONGO_INITDB_AUTHDATABASE: admin
      
   
    ports:
      - 27017:27017
    networks:
      - server
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongodb:27017/DB?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    networks:
      - server
networks:
  server: